name: Generate Gradle Wrapper

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '7.5'

      - name: Generate Gradle Wrapper
        run: gradle wrapper --gradle-version 7.5 --distribution-type all

      - name: Commit Gradle Wrapper files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: Add Gradle Wrapper files"
          file_pattern: "gradlew gradlew.bat gradle/"
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions <actions@github.com>"
